#if !canImport(ObjectiveC)
import XCTest

extension BacktraceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BacktraceTests = [
        ("testCaptureFromBridgedError", testCaptureFromBridgedError),
        ("testCaptureFromLocalError", testCaptureFromLocalError),
        ("testDebugSymbols", testDebugSymbols),
        ("testDebugSymbolsPerformance", testDebugSymbolsPerformance),
        ("testSymbols", testSymbols),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BacktraceTests.__allTests__BacktraceTests),
    ]
}
#endif
